// Regenerates lib/staticStrings.ts from the l10n() call sites.
//
//   node dev/generateStaticStrings.mjs
//
// lib/__tests__/staticStrings.test.ts fails when the file is out of step with the calls,
// which is the reminder to run this after adding or changing a string.
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");

const sourceFiles = (dir) => {
  const found = [];
  for (const entry of readdirSync(dir)) {
    // collectL10nCalls.ts documents the call shape in a comment, which would
    // otherwise be scanned as a real string.
    if (
      entry === "node_modules" ||
      entry === "__tests__" ||
      entry === "collectL10nCalls.ts" ||
      entry.startsWith(".")
    )
      continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) found.push(...sourceFiles(full));
    else if (/\.tsx?$/.test(entry)) found.push(full);
  }
  return found;
};

// Keep in step with lib/collectL10nCalls.ts (duplicated because this script runs as plain
// JavaScript, with no TypeScript loader).
const CALL = /\bl10n\(\s*("(?:[^"\\]|\\.)*")\s*,\s*("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')/g;
const unquote = (literal) =>
  JSON.parse(literal.startsWith("'") ? `"${literal.slice(1, -1).replace(/"/g, '\\"')}"` : literal);

const strings = new Map();
for (const dir of ["components", "lib"]) {
  for (const file of sourceFiles(join(repoRoot, dir))) {
    const source = readFileSync(file, "utf8");
    for (const match of source.matchAll(CALL)) {
      strings.set(unquote(match[1]), unquote(match[2]));
    }
  }
}

const entries = [...strings.entries()].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
const body = entries
  .map(([id, english]) => `  ${JSON.stringify(id)}: ${JSON.stringify(english)},`)
  .join("\n");

writeFileSync(
  join(repoRoot, "lib", "staticStrings.ts"),
  `// Generated by dev/generateStaticStrings.mjs from the l10n() calls in the source.\n` +
    `// Do not edit by hand: change the call site and run the script again.\n` +
    `//\n` +
    `// A "Common." or "EditTab." ID is one Bloom already has a translation for; the rest\n` +
    `// are this editor's own, under "AiImageEditor.".\n` +
    `export const STATIC_IMAGE_EDITOR_STRINGS: Record<string, string> = {\n${body}\n};\n`,
  "utf8",
);

console.log(`Wrote ${entries.length} strings to lib/staticStrings.ts`);
